version: 2

sources:
  - name: staging
    database: dbt-projects-451303
    schema: trips_data_all
    location: europe-west2
#    database: "{{ env_var('DBT_DATABASE', 'taxi-rides-ny-339813-412521') }}"
#    schema: "{{ env_var('DBT_SCHEMA', 'trips_data_all') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata